#!/bin/bash
set -euo pipefail

# =============================================
# Issue 处理脚本
# 接收 Issue 编号，创建分支 → 实现 → 测试 → PR
# =============================================

ISSUE_NUM="$1"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
MAX_RETRIES=${MAX_RETRIES:-3}

cd "$REPO_DIR"

echo "============================================"
echo "处理 Issue #${ISSUE_NUM}"
echo "============================================"

# ---- 1. 获取 Issue 详情 ----
ISSUE_DATA=$(gh issue view "$ISSUE_NUM" --json title,body,labels)
ISSUE_TITLE=$(echo "$ISSUE_DATA" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])")
ISSUE_BODY=$(echo "$ISSUE_DATA" | python3 -c "import sys,json; print(json.load(sys.stdin)['body'])")
ISSUE_TYPE=$(echo "$ISSUE_DATA" | python3 -c "
import sys, json
data = json.load(sys.stdin)
labels = [l['name'] for l in data['labels']]
title_lower = data['title'].lower()
if 'bug' in labels:
    print('bug')
elif 'feature' in labels or 'enhancement' in labels:
    print('feature')
elif any(w in title_lower for w in ['bug', '修复', '错误', '异常', '崩溃', '闪退', 'fix']):
    print('bug')
else:
    print('feature')
")

echo "标题: ${ISSUE_TITLE}"
echo "类型: ${ISSUE_TYPE}"

# ---- 2. 创建分支 ----
BRANCH_PREFIX="fix"
if [ "$ISSUE_TYPE" = "feature" ]; then
    BRANCH_PREFIX="feat"
fi

# 从 Issue 标题生成简短描述（中文标题可能生成空 slug，用 issue 编号兜底）
SLUG=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | cut -c1-40 | sed 's/-$//')
if [ -z "$SLUG" ]; then
    SLUG="issue-${ISSUE_NUM}"
fi
BRANCH_NAME="${BRANCH_PREFIX}/issue-${ISSUE_NUM}-${SLUG}"

echo "分支: ${BRANCH_NAME}"

# 确保 main 是最新的
git fetch origin main
git checkout origin/main
git checkout -b "$BRANCH_NAME"

# ---- 3. 构建 Agent Prompt 并写入临时文件 ----
PROMPT_FILE=$(mktemp)
trap "rm -f $PROMPT_FILE" EXIT

if [ "$ISSUE_TYPE" = "bug" ]; then
    cat > "$PROMPT_FILE" <<PROMPT_EOF
你需要修复一个 Bug。

## Issue #${ISSUE_NUM}: ${ISSUE_TITLE}

## Bug 描述
${ISSUE_BODY}

## 你的任务
1. 阅读相关源代码，理解 Bug 的根因
2. 实现修复
3. 确保修复不会破坏现有功能
4. 如果项目有测试，确保现有测试仍然通过
5. 如果可以，为这个 Bug 添加一个回归测试

## 约束
- 只修改与 Bug 相关的文件，不要做无关的改动
- 保持代码风格一致
- 不要删除或跳过现有测试
PROMPT_EOF
else
    cat > "$PROMPT_FILE" <<PROMPT_EOF
你需要实现一个新功能。

## Issue #${ISSUE_NUM}: ${ISSUE_TITLE}

## 功能描述
${ISSUE_BODY}

## 你的任务
1. 阅读项目结构和现有代码
2. 实现该功能
3. 为新功能编写测试
4. 确保所有测试通过

## 约束
- 遵循现有的代码组织和风格
- 新文件放在合理的位置
- 不要修改与该功能无关的代码
PROMPT_EOF
fi

# ---- 4. 调用 Claude Code ----
gh issue comment "$ISSUE_NUM" --body "🤖 正在实现修复..."

RETRY_COUNT=0
SUCCESS=false

while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo ""
    echo "--- 尝试 ${RETRY_COUNT}/${MAX_RETRIES} ---"

    # 通过管道传递 prompt，避免长参数中的特殊字符导致解析出错
    if cat "$PROMPT_FILE" | claude -p --dangerously-skip-permissions 2>&1; then
        echo "Agent 执行完成"
    else
        echo "Agent 执行出错，继续检查..."
    fi

    # ---- 5. 检查是否有代码变更 ----
    if git diff --quiet && git diff --cached --quiet; then
        echo "Agent 没有产生代码变更"
        if [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; then
            echo "重试..."
            continue
        fi
        # Agent 跳过
        gh issue edit "$ISSUE_NUM" \
            --add-label "claude-skipped" \
            --remove-label "claude-in-progress"
        gh issue comment "$ISSUE_NUM" --body "⚠️ Agent 无法自动处理此 Issue，已转人工处理。"
        git checkout main
        git branch -D "$BRANCH_NAME" 2>/dev/null || true
        exit 1
    fi

    # ---- 6. 提交变更 ----
    git add -A
    git commit -m "$(cat <<EOF
[${BRANCH_PREFIX} #${ISSUE_NUM}] ${ISSUE_TITLE}

Fixes #${ISSUE_NUM}
EOF
)"

    # ---- 7. 跑测试 ----
    echo "--- 跑测试 ---"
    gh issue edit "$ISSUE_NUM" \
        --add-label "claude-testing" \
        --remove-label "claude-in-progress"
    gh issue comment "$ISSUE_NUM" --body "🧪 正在跑测试..."

    if npm test 2>&1; then
        echo "测试通过"
        SUCCESS=true
        break
    else
        echo "测试失败（尝试 ${RETRY_COUNT}/${MAX_RETRIES}）"
        if [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; then
            gh issue comment "$ISSUE_NUM" --body "❌ 测试未通过，Agent 正在重试... (${RETRY_COUNT}/${MAX_RETRIES})"
            echo "上次的代码变更导致测试失败。请查看测试输出，修复问题，确保所有测试通过。" | claude -p --dangerously-skip-permissions 2>&1 || true
        fi
    fi
done

if [ "$SUCCESS" = false ]; then
    echo "所有重试均失败"
    gh issue edit "$ISSUE_NUM" \
        --add-label "claude-failed" \
        --remove-label "claude-testing"
    gh issue comment "$ISSUE_NUM" --body "❌ Agent 尝试了 ${MAX_RETRIES} 次仍无法通过测试，已转人工处理。"
    git checkout main
    git branch -D "$BRANCH_NAME" 2>/dev/null || true
    exit 1
fi

# ---- 8. 推送并创建 PR ----
echo "--- 创建 PR ---"
git push -u origin "$BRANCH_NAME"

PR_BODY=$(cat <<EOF
## Summary
自动处理 Issue #${ISSUE_NUM}: ${ISSUE_TITLE}

## Changes
此 PR 由 Claude Agent 自动生成，修复了上述 Issue 中描述的问题。

## Test plan
- [x] 所有现有测试通过
- [x] Agent 已验证修复有效性

Fixes #${ISSUE_NUM}

---
🤖 Generated by Claude Agent
EOF
)

PR_URL=$(gh pr create \
    --title "[${BRANCH_PREFIX} #${ISSUE_NUM}] ${ISSUE_TITLE}" \
    --body "$PR_BODY" \
    --head "$BRANCH_NAME" \
    --base main)

echo "PR 已创建: ${PR_URL}"

# ---- 9. 自动合并 PR ----
echo "--- 自动合并 PR ---"
if gh pr merge "$PR_URL" --squash --delete-branch 2>&1; then
    echo "PR 已自动合并"
    gh issue edit "$ISSUE_NUM" \
        --add-label "claude-ready-for-review" \
        --remove-label "claude-testing"
    gh issue comment "$ISSUE_NUM" --body "✅ 修复已完成并自动合并: ${PR_URL}"
else
    echo "自动合并失败，转为等待人工 Review"
    gh issue edit "$ISSUE_NUM" \
        --add-label "claude-ready-for-review" \
        --remove-label "claude-testing"
    gh issue comment "$ISSUE_NUM" --body "⚠️ 自动合并失败，PR 已创建: ${PR_URL}

请手动 Review 后合并。"
fi

echo "============================================"
echo "Issue #${ISSUE_NUM} 处理完成"
echo "PR: ${PR_URL}"
echo "============================================"
