# 创建 scripts/stats.sh
#!/bin/bash
echo "=== Agent 处理统计 ==="
echo ""
echo "待处理:    $(gh issue list --label claude-pending --state open --json number | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))')"
echo "处理中:    $(gh issue list --label claude-in-progress --state open --json number | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))')"
echo "测试中:    $(gh issue list --label claude-testing --state open --json number | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))')"
echo "等 Review: $(gh issue list --label claude-ready-for-review --state open --json number | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))')"
echo "失败:      $(gh issue list --label claude-failed --state open --json number | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))')"
echo "跳过:      $(gh issue list --label claude-skipped --state open --json number | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))')"
echo ""
echo "已关闭的 Agent PR: $(gh pr list --state merged --search "Generated by Claude Agent" --json number | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))')"
